export const SHOW_DESCRIPTION_TOGGLED = 'form.field.SHOW_DESCRIPTION_TOGGLED'
export const SHOW_PLACEHOLDER_TOGGLED = 'form.field.SHOW_PLACEHOLDER_TOGGLED'
export const IS_INTEGER_TOGGLED = 'form.field.IS_INTEGER_TOGGLED'
export const ALLOW_MULTIPLE_TOGGLED = 'form.field.ALLOW_MULTIPLE_TOGGLED'
export const TITLE_UPDATED = 'form.field.TITLE_UPDATED'
export const ENUM_UPDATED = 'form.field.ENUM_UPDATED'
export const ENUM_ADDED = 'form.field.ENUM_ADDED'
export const ENUM_REMOVED = 'form.field.ENUM_REMOVED'
export const TRAVERSE_ARRAY_UPDATED = 'form.field.TRAVERSE_ARRAY_UPDATED'

