export const SHOW_DESCRIPTION_TOGGLED = 'form.field.SHOW_DESCRIPTION_TOGGLED'
export const TITLE_UPDATED = 'form.field.TITLE_UPDATED'
export const DESCRIPTION_UPDATED = 'form.field.DESCRIPTION_UPDATED'
export const ENUM_UPDATED = 'form.field.ENUM_UPDATED'
export const ENUM_ADDED = 'form.field.ENUM_ADDED'
export const ENUM_REMOVED = 'form.field.ENUM_REMOVED'
export const TRAVERSE_ARRAY_UPDATED = 'form.field.TRAVERSE_ARRAY_UPDATED'
