export const SHOW_DESCRIPTION_TOGGLED = 'form.field.SHOW_DESCRIPTION_TOGGLED'
export const TITLE_UPDATED = 'form.field.TITLE_UPDATED'
export const DESCRIPTION_UPDATED = 'form.field.DESCRIPTION_UPDATED'

